language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "grace-shopper-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the grace-shopper
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  skip_cleanup: true
  provider: heroku
  app: beats-store
  api_key:
    secure: X0nF1r8uro3V+p0GIttLEEcUuvrcixTUcDPcCVRDWKWXr88Tg/S36LB0KmHK0MZhLvlbLi5XAD4mxCO5geXDT674e3il6PLHtb4lVPdyRvm79CcO4a7Eyd/1NonQWALtKSQBZII01q2Q6ihU6MbwQyEtI008s+t25RIoUrox1lF5EKk8w2UYgygBo8UxvX1zLrC48c/v9YikXixJndqj/gxWfQ6/nroDHqh+JiX2eAqXIsDvIe038mjBAfsYo8SiXMjIlr8AOM5YIv+UxDayf64Cf9BwWqAwtPaF03aI75DK0GpuDt5/fXkXhMZL9PhAikh5W8EINREFAfiUeEEzrKEZRWYwV5l7+emaNhqO4PNrkt+Lu0A0X5ooJTJkxQFC+5/s8qUoIWl5pIhJXkKkEXYhfO/dk0LMmmoa1CoFmE3VamBXrWnuZREExhBqS946YSRKnWtcfB9S0FMnKa8Aqxl29T6jSaohPoIOwrC5UKY3iciGJamfeh/uqiPucXcPh+DM4ZZ0rNeNB4x8EPQzwGdcBz52HxuYlCZvI4cYnSothd5jdtXs6kgAhxS/Gxc8jmqNNAPKnPpfiDjTdiVEP6oeohylScq7x8pf/hHdbfcY75iG1BksVrlVWaVexZszxNZ35LISWY3+uJzclMNdYCc/SZ2ZTySitBmeOVmhg8M=
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
