language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment (OSyst linux OS)
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "grace-shopper-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json) ==== before anything this creates all that we need,  this should create grace-shopper-test... virtual machine b4 running your code
script:
  - npm test # test the grace-shopper
  - npm run build-client # make the bundle
# before_deploy: # omit node_modules, since we set skip_cleanup below
#   - rm -rf node_modules
deploy: # see README for details on these keys
  skip_cleanup: true
  provider: heroku
  app: "beats-store"
  api_key:
    secure: Dr6/uEXj9c+6iaVi67fndPzuYC0zGhX0Cs7e0pkO2La3VfqAkmDC7MkB8qZl9foSMY3iCBubwKSF5cvTRJQpBkc6p1LD47XVDKBcEFXLJxrF+K1JUr8B+pEbuoFgPwjR0ZiI+rQf0ZY+O8JQJdKhy5GdAWHFrbINYW9hbD1mg3t/ZjDxRKUPxDCuW3wxAOV7Is+pysPR1RWHNadS/73bYtBNx4PCMx4vl5r3Qfzg7wVma3R+4QBT1mAPO7cR3whS85zQ9ZicS7I1AzhZ9MNH710bF9bPde/Anad1FTHuPFun1bvS4uDZgmQeKOCjqeDAzW35HsOzgLnPDfJBYeSRfNb6+x9xUAn0Dz9W5eUYFO1u0ZvOJd9LATThqH+B0DJDS3vlslare/mFZ1pA3xnvVm+F28qL64ImbM3cpKBkbNEAiBI3Q74mKY2hHYQZJY+yWMZUNsKTo736ib/aAXRauGayVSHzyCtrBmG8TGCyII7/467IGplCuJQlbf0NaWXwWqZLRuPfg0FRfOvISEQJdkueutkkmRzZ2L6naVw4gUzGhXgvQxOyf0jxUCqWZo+gNr5nhxdSSYgQZKYJu4dSRNkBdWCC9xaUOvek3l+DpdiGehuxn21yXTW9tf646GjubNBxBcI6/jWahMWz5BlbD4w2rhB1WMM78M7WTzPlkYc=
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
