language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "grace-shopper";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the grace-shopper
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: "https://beats-store.herokuapp.com"
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: iqEeQh334BsbyMDPWKd/e0Ja1mBAHxjCGdh+Q8eCDUnC4ypk5vvVdb5mYEIbuIyQ/OePG5kISf5OiVIy2g1f50RUMT5AuV4cAhdTfSXo8tpNepaPAF4gC3M4zLgBFMXejWIi1xV9yAOEtRPoQ0SubBbxCDuUcs5vqurnu2pYZtMURSwyWc+SBN4bSm0tsiKaFobXEcjUJTT2egVG5GHO0gRRrR3G7t9Ec3ZdxkwArKgJT7YBj05l3WZEE41Srm+vosE9B5UTQXJh6eFjbvy1y+/CL7n1/ywt99pm8lPfWqKer7VLkelrdcIAwxslbt56q8GCmZt2iQSiKK8buV3RaUCQ8lcaM1hJr/44KMPAoLwPbdhZamC2Bp8oPCqGcf0xoWfpPLac35OsmUIF2GT845xX5MPN0gMPrT6B7vQ2+v7mplJ9fMjAXUzgAQMEh3L0STils6GDVfnUyHb2AJJIld/6LvqyhwmpzNlYu35tIPFaUwYRXbU9qMZKbCJEksuN4whay2NRKd1f3RFW7+jcCcHHWWuRRB6BY0Dov3pGcNIfulDuKlt+/lCNM8sm69TKp4LJPucJaUeoq/YpOx52X6ankqTAfatFSBDkAxJ8mZKI22/y/1Ztm5tOlTso7kLr5SVnEL9Erd/yvyI1IYF5MXI0tz/JV4SIx0ivW1vSSQ0=
